@endpoint = https://rpm7j0f834.execute-api.ap-southeast-2.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces/
###

PUT {{endpoint}}/spaces?spaceId=20ccf2c7-3c78-4639-83df-9d48927c2a1f
Content-Type: application/json

{
    "location": "New Zeeeeland"
}
###



GET {{endpoint}}/spaces?location=London
###


POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Beijing",
    "name": "China"
}
###

DELETE {{endpoint}}/spaces?spaceId=29b3ca36-e22e-4be5-b386-f03f1d7fbdc9
###